
spring:
  # 连接池的补充配置，应用到上面所有数据源中
  datasource:
    # dynamic-datasource-spring-boot-starter 动态数据源的配置内容
    dynamic:
      # 设置默认数据源，默认值为 master
      primary: users
      datasource:
        # 用户数据源配置
        users:
          username: root
          password: root
          url: jdbc:mysql://localhost:3306/sb41_user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
          driver-class-name: com.mysql.cj.jdbc.Driver
        # 订单数据源配置
        orders:
          username: root
          password: root
          url: jdbc:mysql://localhost:3306/sb41_order?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
          driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis的相关配置
mybatis:
  # mapper配置文件
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.vic.sb41.entity
#  IDENTITY: MYSQL #取回主键的方式
#  notEmpty: false #insert和update中，是否判断字符串类型!=''
  configuration:  #进行自动映射时，数据以下划线命名，如数据库返回的"order_total"命名字段是否映射为class的"orderTotal"字段。默认为false
    map-underscore-to-camel-case: true






