server:
  port: 1919

# 异步任务配置
async:
  task:
    # 最小工作线程
    minSize: 5
    # 最大工作线程
    maxSize: 30
    # 队列数量
    queues: 200
    # 允许空闲时间(秒)
    keepAlive: 60
    # 线程名称前缀
    namePrefix: "taskExecutor-"