
server:
  port: 1236

# jwt configuration
audience:
  # the audience
  clientId: 123
  # the original string is <i am your dady>
  base64Secret: aSBhbSB5b3VyIGRhZHk=
  # issuer
  name: victor
  # 48 hours
  expireSecond: 172800

# filter switch
filter:
  switch: true