
server:
  port: 1236

# jwt configuration
audience:
  # the audience
  client-id: 123
  # the original string is <i am your dady>
  base64-secret: aSBhbSB5b3VyIGRhZHk=
  # issuer
  name: victor
  # 48 hours
  expire_second: 172800

# filter switch
filter:
  switch: true