
server:
  port: 1236

# jwt configuration
audience:
  # the audience
  client-id: 123
  # the original string is <i am your dady>
  base64-secret: aSBhbSB5b3VyIGRhZHk=
  # issuer
  name: victor
  # 48 hours
  expire_second: 172800

# filter switch
filter:
  switch: false

custom:
# 对象集合
  students[0]:
    name: victor
    age: 18
  students[1]:
    name: justin
    age: 19
  studentList:
    - name: diana
      age: 20
    - name: july
      age: 21

