server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sb40_01?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

# mybatis的相关配置
mybatis:
  # mapper配置文件
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.vic.sb37.entity
