
# 应用访问端口
server:
  port: 1915
management:
  endpoints:
    web:
      exposure:
        include: "*" # 开启暴露所有的端点信息， 默认只打开health,info，这里只写一个表示只打开这个端点 如：loggers
        exclude: # 公开所有端点，但是要排除loggers和env端点
          - loggers
          - env
      base-path: /haha # 调整端点的前缀路径为/haha, http://localhost:1915/haha，访问endpoint使用http://localhost:${management.server.port}/haha 地址
      path-mapping:
        health: healtha # 将端点映射到不同的路径，当映射后原来端点ID不可访问
    enabled-by-default: true # 设置所有端点的开启默认值，为false时啥也没有了
  endpoint:
    health: # 这里只能是端点名称，不能是映射之后的名称，如: 上面的映射：health: healtha，这里配置为healtha不起作用
      show-details: always # 显示健康具体信息，默认不会显示详细信息
    httptrace:
      enabled: true # 启用httptrace端点，为false时，http://localhost:1915/haha目录下不返回httptrace
  server:
    port: 2011 # 监控端口号 Management endpoint HTTP port(uses the same port as the application by default)
spring:
  security: # http安全机制
    user:
      name: vic
      password: vic
      roles: ADMIN
# 添加info端点内容
info:
  encoding:
    @project.build.sourceEncoding@
  traget:
    @java.version@
  name:
    @project.name@
  description:
    @project.description@
#malware: # 自定义malware端点, 貌似不支持这种写法
#  encoding:
#    @project.build.sourceEncoding@